pipeline:

  #####################################################################################################
  # 2. Promote gem to Nexus
  #####################################################################################################
  build:
    when:
      branch: master
    image: 714782054810.dkr.ecr.eu-west-2.amazonaws.com/base-images/qe-ruby:2.7.0
    secrets: [NEXUS_USER, NEXUS_PASSWORD]
    commands:
      - apk add --update git --update alpine-sdk  --no-cache
      - gem install bundler
      - bundle
      - gem install nexus
      - gem build parallel_report_portal.gemspec
      - gem nexus --url https://nexus.int-ac.dvla.gov.uk/repository/gem-private/  parallel_report_portal*gem